# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none # Disable CI triggers, but schedule/pipeline trigger still works.

# resources:
#   pipelines: 
#     - pipeline: upstream-pipeline
#       source: sunb0002.transferfile
#       trigger: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello Fate Zero!
  displayName: 'Install Node.js (just echo)'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'MySonar'
    scannerMode: 'MSBuild'
    projectKey: 'HelloADO'
  
- task: SonarQubeAnalyze@5